---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Vhost configuration.
- import_tasks: vhosts.yml

- name: Add a user to a password file and ensure permissions are set
  community.general.htpasswd:
    path: /etc/nginx/passwdfile
    name: promtail
    password: 'MIIGti1YnBM5Dheql39ugtpVygGc9'
    owner: root
    group: nginx
    mode: 0640

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: validate nginx configuration
  command: /usr/sbin/nginx -t -c /etc/nginx/nginx.conf
  changed_when: false
